raft:
  nodes:
    - "127.0.0.1:8000"
    - "127.0.0.1:8001"
    - "127.0.0.1:8002"
  election_timeout: 300
  election_timeout_random: 200
  heartbeat_interval: 100

master:
  nMaster: 3
  files:
    - "pg-being_ernest.txt"
    - "pg-dorian_gray.txt"
    - "pg-frankenstein.txt"
    - "pg-grimm.txt"
    - "pg-huckleberry_finn.txt"
    - "pg-metamorphosis.txt"
    - "pg-sherlock_holmes.txt"
    - "pg-tom_sawyer.txt"
  nReduce: 10

worker:
  nWorker: 1
  plugin: Inverted_index.so


log:
  level: "info"
  masterfile: "../logs/master"
  workerfile: "../logs/worker"
