raft:
  nodes:
    - "127.0.0.1:8000"
    - "127.0.0.1:8001"
    - "127.0.0.1:8002"
  election_timeout: 300
  election_timeout_random: 200
  heartbeat_interval: 100

master:
  nMaster: 3
  files:
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-being_ernest.txt"
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-dorian_gray.txt"
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-frankenstein.txt"
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-grimm.txt"
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-huckleberry_finn.txt"
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-metamorphosis.txt"
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-sherlock_holmes.txt"
    - "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/assets/pg-tom_sawyer.txt"
  nReduce: 10

worker:
  nWorker: 3
  plugin: /home/zhuyicheju/Desktop/Mapreduce-on-Raft/main/Inverted_index.so


log:
  level: "info"
  masterfile: "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/logs/master"
  workerfile: "/home/zhuyicheju/Desktop/Mapreduce-on-Raft/logs/worker"
